name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the deployment on push events to the main branch.
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment.
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3  # Checks out the repository code.

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version.

      - name: Install Dependencies
        run: npm install  # Installs the project dependencies.

      - name: Build
        run: npm run build  # Builds your Vite React project. Make sure your 'build' script in package.json is correctly set up.

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # The output directory after the build. Adjust if your build output directory is different.
